### ISSUE TITLE
swintransformer.py

### ISSUE THREAD

**Issue by cyn-pyk** [LYMDLUT/yolov5-swin#1]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

您好  想问您一下  swintransformer.py中的SwinTransformerBlock类中的第五行这个"Conv"是在common.py中导入进来的吗？谢谢

### Additional

![)($C1YC(X4SH0CS3EV56NWY](https://user-images.githubusercontent.com/83932472/171392923-3c9c8a5e-966e-45db-9017-d7f94b74bd4a.png)

**Comment by LYMDLUT** [comment]
Sorry,it is a bug
